---
- hosts: devsecops_kolide_eip
  become: true
  name: Harden server via GSA-approved ansible role

  roles:
  - gsa_ubuntu_16_hardening

  vars_files:
    - ../group_vars/devsecops_kolide_eip/vars.yml